const screens=[...document.querySelectorAll('.screen')];const modal=document.querySelector('#modal');const modalTitle=document.querySelector('#modalTitle');const modalText=document.querySelector('#modalText');const modalIcon=document.querySelector('#modalIcon');let current='cover';
function show(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));current=name;window.scrollTo({top:0,behavior:'smooth'});if(name==='final')celebrate(110)}
function openModal(title,text,icon='💗'){modalTitle.textContent=title;modalText.textContent=text;modalIcon.textContent=icon;modal.classList.remove('hidden')}
function closeModal(){modal.classList.add('hidden')}
document.querySelector('#startBtn').addEventListener('click',()=>{celebrate(36);setTimeout(()=>show('story'),280)});document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.next)));document.querySelector('#finishBtn').addEventListener('click',()=>show('final'));document.querySelector('#replayBtn').addEventListener('click',()=>show('cover'));document.querySelector('#closeModal').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.querySelectorAll('.reveal-card').forEach(card=>card.addEventListener('click',()=>openModal(card.dataset.title,card.dataset.text,card.querySelector('span').textContent)));
document.querySelectorAll('.flip-card').forEach(card=>card.addEventListener('click',()=>card.classList.toggle('flipped')));
document.querySelectorAll('.surprise-choice').forEach((card,i)=>card.addEventListener('click',()=>{const icons=['🎁','🌸','🚗'];celebrate(28);openModal(card.querySelector('strong').textContent,card.dataset.surprise,icons[i])}));
const questions=[
 {q:'¿Qué día te mandé mi primer mensaje?',a:['11 de agosto de 2025','14 de noviembre de 2025','1 de enero de 2025'],c:0,ok:'¡Sí! Ahí empezó nuestra historia. 💌',no:'Pista: fue un 11 de agosto… pero igual te quiero. 💗'},
 {q:'¿Cuál es nuestra fecha especial?',a:['14 de noviembre','14 de febrero','11 de agosto'],c:0,ok:'¡Correcto! Esa fecha es muy nuestra. ❤️',no:'Casi… recuerda el 14 de noviembre. ✨'},
 {q:'¿Qué frase es muy nuestra?',a:['Te amo mucho','eh eh eh eh eh','Hasta mañana'],c:1,ok:'¡Esa es! eh eh eh eh eh ❤️',no:'La respuesta hace: eh eh eh… 😄'},
 {q:'¿Qué recuerdo tiene un lugar súper especial?',a:['Nuestro primer beso','La primera lluvia','Una película cualquiera'],c:0,ok:'Exacto, un recuerdo que guardo con mucho cariño. 💗',no:'Pista: tiene muchos corazoncitos. 💗'},
 {q:'¿Qué quiero seguir haciendo contigo?',a:['Crear muchos recuerdos','No salir nunca','Olvidar las aventuras'],c:0,ok:'¡Exactamente! Que vengan más momentos bonitos. 🚗✨',no:'La respuesta siempre será: más recuerdos juntos. 💞'}
];let qi=0,score=0,answered=false;const quizBox=document.querySelector('#quizBox'),quizNext=document.querySelector('#quizNext');
function drawQuiz(){answered=false;quizNext.classList.add('hidden');const x=questions[qi];quizBox.innerHTML=`<div class="quiz-progress">Pregunta ${qi+1} de ${questions.length}</div><h3 class="quiz-question">${x.q}</h3><div class="answers">${x.a.map((t,i)=>`<button class="answer" data-i="${i}">${t}</button>`).join('')}</div><div class="feedback hidden"></div>`;quizBox.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',answer))}
function answer(e){if(answered)return;answered=true;const pick=+e.currentTarget.dataset.i,x=questions[qi],buttons=quizBox.querySelectorAll('.answer');buttons[x.c].classList.add('correct');if(pick===x.c){score++;}else e.currentTarget.classList.add('wrong');buttons.forEach(b=>b.disabled=true);const fb=quizBox.querySelector('.feedback');fb.textContent=pick===x.c?x.ok:x.no;fb.classList.remove('hidden');quizNext.textContent=qi===questions.length-1?'Ver resultado 💗':'Siguiente pregunta →';quizNext.classList.remove('hidden')}
quizNext.addEventListener('click',()=>{if(qi<questions.length-1){qi++;drawQuiz()}else{const msg=score===5?'¡Perfecto! Eres un novio experto y conoces muy bien nuestro universo. 💗':score>=3?'¡Lo hiciste increíble! Tenemos muchos recuerdos para seguir aprendiendo juntos. 💞':'Lo importante es que todavía tenemos miles de recuerdos por crear. ❤️';openModal('💗 Terminaste el juego 💗',`Acertaste ${score} de ${questions.length}. ${msg}`,'🏆');setTimeout(()=>show('memories'),450)}});drawQuiz();
function celebrate(n=55){const box=document.querySelector('#confetti');const colors=['#ff4f85','#ffd25b','#7c68d5','#6ed8c4','#fff'];for(let i=0;i<n;i++){const d=document.createElement('i');d.className='conf';d.style.left=Math.random()*100+'%';d.style.background=colors[i%colors.length];d.style.animationDuration=(1.8+Math.random()*2)+'s';d.style.animationDelay=(Math.random()*.45)+'s';d.style.transform=`rotate(${Math.random()*180}deg)`;box.appendChild(d);setTimeout(()=>d.remove(),4400)}}
function floating(){const sky=document.querySelector('#sky'),d=document.createElement('span');d.className='float';d.textContent=Math.random()>.55?'♥':'✦';d.style.left=Math.random()*100+'%';d.style.bottom='-30px';d.style.color=Math.random()>.5?'#ff75a2':'#fff';d.style.fontSize=(13+Math.random()*16)+'px';d.style.animationDuration=(7+Math.random()*6)+'s';sky.appendChild(d);setTimeout(()=>d.remove(),14000)}setInterval(floating,1050);for(let i=0;i<7;i++)setTimeout(floating,i*160);
